# project_code: cmm, apb_d7, etc.
name:

recipe: drupal9

config:
  # default: web | lightning: docroot
  webroot: web
  php: '7.4'

  # Optionally activate xdebug
  #
  # Another option is to set this config in .lando.local.yml
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  # xdebug: true

# Additional services and features.
services:
  # Frontend and Cypress Tests.
  nodejs:
    type: node
    port: 8000
    globals:
      next-cli: latest

# Custom Lando commands
tooling:
  deploy:
    description: "lando deploy \tDeploys current branch to env. See README.md for workflow."
    cmd:
      - appserver: /app/.localci/deploy.sh
  fresh:
    description: Run all the things to get local to a fresh state for this branch. (Checkout master branch first if starting a new feature.)
    cmd:
      - appserver: echo && echo "Running composer install..." && composer install
      - node-cli: echo && echo "Building themes..." && /app/scripts/theme.sh -a
      - appserver: echo && echo "Resetting drupal..." && drush updb -y && drush cim -y && drush cr
  'fresh:db <db>':
    description: Same as fresh but also takes path to db file to import first.
    cmd:
      - database: /helpers/sql-import.sh
      - appserver: echo && echo "Running composer install..." && composer install && true
      - node-cli: echo && echo "Building themes..." && /app/scripts/theme.sh -a && true
      - appserver: echo && echo "Resetting drupal..." && drush updb -y && drush cim -y && drush cr && true
  node:
    service: nodejs
  npm:
    service: nodejs
  npx:
    service: nodejs
  phpcbf:
    service: appserver
    description: "lando phpcbf [path]\tCode Beautification. (Auto fix coding standards.)"
    cmd: /app/vendor/bin/phpcbf --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer && /app/vendor/bin/phpcbf -p --standard=Drupal,DrupalPractice --extensions=php,inc,profile,module,install,profile
  phpcs:
    service: appserver
    description: "lando phpcs [path]\tCode Sniffer. (Check coding standards.)"
    cmd: /app/vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer && /app/vendor/bin/phpcs -p --standard=Drupal,DrupalPractice --extensions=php,inc,profile,module,install,profile
  phpmd:
    service: appserver
    description: "lando phpmd [path] [format] [ruleset]\tMess Detector."
    cmd: /app/vendor/bin/phpmd
  reset:
    service: appserver
    description: "updb, cim, cr"
    cmd:
      - drush updb -y
      - drush cim -y
      - drush cr
      - drush uli
  testuser:
    service: appserver
    description: prepare drupal for testing
    cmd:
      - drush ucrt test --mail=test-test@wayofbjj.com --password=changethis
      - drush urol administrator test
  ts:
    service: appserver
    description: "Theme: Sub - `ts [Theme Name]` Create subtheme from Monk Theme Base"
    cmd:
      - drush --include=/app/web/themes/custom/monk_theme monk_theme:create
env_file:
  - .env
