# Rename this file to .lando.yml to use, or delete if you already have one.
# Named start.lando.yml to not conflict with projects installed with lando mw install.

# project_code: cmm, apb_d7, etc.
name:

# drupal8 | drupal7 | wordpress
recipe: drupal8

config:
  # default: web | lightning: docroot
  webroot: web

  php: '7.1'

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: true


  # *********************************************************************************
  # ****   No need to change anything below, unless you know what you're doing.  ****
  # ****                    And have a very specific need.                       ****
  #**********************************************************************************

# Additional services and features.
services:
  # Theme.
  node-cli:
    type: node:10

    globals:
      gulp-cli: "latest"


# Custom Lando commands
tooling:
  build:
    service: appserver
    description: "Build the project. \n  -c Clean build. \n  -l (live) Build production code. composer install --no-dev \n -t Theme build \n  -w Run theme watcher \n  -y Confirm prompts."
    cmd:
      - /app/scripts/build.sh
      - -c
  build:reset:
    service: appserver
    description: "Run local-dev script. (updb, cim, cr, uli)"
    cmd:
      - /app/scripts/reset.sh
  build:theme:
    service: node-cli
    description: "Compile the theme."
    cmd:
      - /app/scripts/build.sh
      - -t
  gulp:
    service: node-cli
  node:
    service: node-cli
  npm:
    service: node-cli
  mw:
    service: appserver
  test:phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd:
      - ./vendor/bin/phpunit
  test:vrt:
    service: node-cli
    description: "Use: test:vrt [local|dev|stage|prod]:ref to create reference. test:vrt [local|dev|stage|prod] to run comparision tests."
    cmd:
      - npm
      - run
      - --prefix=/app/tests/vrt
  test:vrt:install:
    service: node-cli
    cmd:
      - npm
      - install
      - /app/tests/vrt
