# Rename this file to .lando.yml to use, or delete if you already have one.
# Named start.lando.yml to not conflict with projects installed with lando mw install.

# project_code: cmm, apb_d7, etc.
name:

# drupal8 | drupal7 | wordpress
recipe: drupal8

config:
  # default: web | lightning: docroot
  webroot: web

  php: '7.3'

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  # xdebug: true


  # *********************************************************************************
  # ****   No need to change anything below, unless you know what you're doing.  ****
  # ****                    And have a very specific need.                       ****
  #**********************************************************************************

# Additional services and features.
services:
  # Theme.
  node-cli:
    type: node:10

# Custom Lando commands
tooling:
  build:
    service: appserver
    description: "Build the project."
    cmd:
      appserver: composer install -d /app
      node-cli: npm install --prefix /app/[webroot]/themes/custom/[theme name]
      node-cli: npm run build --prefix /app/[webroot]/themes/custom/[theme name]
  deploy:
    description: "lando deploy [env]"
    appserver: composer install --no-dev -o -d /app && echo installing
    node-cli: npm install --prefix /app/web/themes/custom/[theme name] && npm run build --prefix /app/web/themes/custom/[theme name] && echo building
    appserver: /app/scripts/deploy.sh
  node:
    service: node-cli
  npm:
    service: node-cli
  reset:
    service: appserver
    description: "updb, cim, cr"
    cmd:
      - drush updb -y
      - drush cim -y
      - drush cr
      - drush uli
  tb:
    service: node-cli
    description: "Compile the theme."
    cmd:
      - npm run build --prefix /app/[webroot]/themes/custom/[theme name]
  ti:
    service: node-cli
    description: "Theme: Install - `ti [theme_name]` (npm install)"
    cmd:
      - npm install --prefix /app/[webroot]/themes/custom/[theme name]
      - npm run build --prefix /app/[webroot]/themes/custom/[theme name]
  tw:
    service: node-cli
    description: "Theme: Watch `tw [theme_name]`"
    cmd:
      - npm run dev --prefix /app/[webroot]/themes/custom/[theme name]
  # Docker is extra slow with xdebug enabled. Turn it on and off as needed without rebuilding.
  # xdebug: https://github.com/lando/lando/issues/1668#issuecomment-507191275
  xon:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xoff:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root

